# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labelDSA2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Moyamoya Label Tool")
        MainWindow.resize(1000, 1017)

        #The first column 下方第一列
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(40, 40, 750, 750))
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 820, 131, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.set_LECA_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_LECA_Button.setObjectName("set_LECA_Button")
        self.gridLayout.addWidget(self.set_LECA_Button, 2, 0, 1, 1)
        self.set_LICA_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_LICA_Button.setObjectName("set_LICA_Button")
        self.gridLayout.addWidget(self.set_LICA_Button, 0, 0, 1, 1)
        self.set_LVA_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_LVA_Button.setObjectName("set_LVA_Button")
        self.gridLayout.addWidget(self.set_LVA_Button, 1, 0, 1, 1)
        self.set_LCCA_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_LCCA_Button.setObjectName("set_LCCA_Button")
        self.gridLayout.addWidget(self.set_LCCA_Button, 3, 0, 1, 1)
        self.set_LSUBA_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_LSUBA_Button.setObjectName("set_LSUBA_Button")
        self.gridLayout.addWidget(self.set_LSUBA_Button, 4, 0, 1, 1)

        #The second column 下方第二列
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 820, 131, 121))

        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.set_RECA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.set_RECA_Button.setObjectName("set_RECA_Button")
        self.gridLayout_2.addWidget(self.set_RECA_Button, 2, 0, 1, 1)
        self.set_RICA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.set_RICA_Button.setObjectName("set_RICA_Button")
        self.gridLayout_2.addWidget(self.set_RICA_Button, 0, 0, 1, 1)
        self.set_RVA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.set_RVA_Button.setObjectName("set_RVA_Button")
        self.gridLayout_2.addWidget(self.set_RVA_Button, 1, 0, 1, 1)
        self.set_RCCA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.set_RCCA_Button.setObjectName("set_RCCA_Button")
        self.gridLayout_2.addWidget(self.set_RCCA_Button, 3, 0, 1, 1)
        self.set_RSUBA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.set_RSUBA_Button.setObjectName("set_RSUBA_Button")
        self.gridLayout_2.addWidget(self.set_RSUBA_Button, 4, 0, 1, 1)

        #The third column  下方第三列
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 820, 131, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.set_LAT_ECA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.set_LAT_ECA_Button.setObjectName("set_LAT_ECA_Button")
        self.gridLayout_3.addWidget(self.set_LAT_ECA_Button, 2, 0, 1, 1)
        self.set_LAT_ICA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.set_LAT_ICA_Button.setMaximumSize(QtCore.QSize(16777208, 16777215))
        self.set_LAT_ICA_Button.setObjectName("set_LAT_ICA_Button")
        self.gridLayout_3.addWidget(self.set_LAT_ICA_Button, 0, 0, 1, 1)
        self.set_LAT_VA_Button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.set_LAT_VA_Button.setObjectName("set_LAT_VA_Button")
        self.gridLayout_3.addWidget(self.set_LAT_VA_Button, 1, 0, 1, 1)
        self.set_CCAp_Button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.set_CCAp_Button.setObjectName("set_CCAp_Button")
        self.gridLayout_3.addWidget(self.set_CCAp_Button, 3, 0, 1, 1)
        self.set_ARCH_Button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.set_ARCH_Button.setObjectName("set_ARCH_Button")
        self.gridLayout_3.addWidget(self.set_ARCH_Button, 4, 0, 1, 1)
        #The fourth column
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(820, 40, 160, 134))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lastImg_Button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.lastImg_Button.setObjectName("lastImg_Button")
        self.gridLayout_4.addWidget(self.lastImg_Button, 1, 0, 1, 1)
        self.load_Button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.load_Button.setObjectName("load_Button")
        self.gridLayout_4.addWidget(self.load_Button, 0, 0, 1, 1)
        self.dump_json_Button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.dump_json_Button.setObjectName("dump_json_Button")
        self.gridLayout_4.addWidget(self.dump_json_Button, 3, 0, 1, 1)
        self.accept_Button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.accept_Button.setObjectName("accept_Button")
        self.gridLayout_4.addWidget(self.accept_Button, 2, 0, 1, 1)

        #The fifth column  下方第四列
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(530, 820, 131, 121))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.remove_Button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.remove_Button.setObjectName("remove_Button")
        self.gridLayout_5.addWidget(self.remove_Button, 2, 0, 1, 1)
        self.set_UnknownAP_Button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.set_UnknownAP_Button.setMaximumSize(QtCore.QSize(16777208, 16777215))
        self.set_UnknownAP_Button.setObjectName("set_UnknownAP_Button")
        self.gridLayout_5.addWidget(self.set_UnknownAP_Button, 0, 0, 1, 1)
        self.set_UnknownLAT_Button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.set_UnknownLAT_Button.setObjectName("set_UnknownLAT_Button")
        self.gridLayout_5.addWidget(self.set_UnknownLAT_Button, 1, 0, 1, 1)
        self.set_CCAd_Button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.set_CCAd_Button.setObjectName("set_CCAd_Button")
        self.gridLayout_5.addWidget(self.set_CCAd_Button, 3, 0, 1, 1)


        #other
        self.PrimaryAngel_label = QtWidgets.QLabel(self.centralwidget)
        self.PrimaryAngel_label.setGeometry(QtCore.QRect(820, 200, 151, 151))
        self.PrimaryAngel_label.setObjectName("PrimaryAngel_label")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(870, 420, 22, 371))
        self.verticalSlider.setProperty("value", 50)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.progress_Bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_Bar.setGeometry(QtCore.QRect(700, 820, 261, 23))
        self.progress_Bar.setProperty("value", 24)
        self.progress_Bar.setObjectName("progress_Bar")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    #用于修改窗口上的文字
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Moyamoya Label Tool"))
        self.imageLabel.setText(_translate("MainWindow", "TextLabel"))
        self.set_LECA_Button.setText(_translate("MainWindow", "LECA"))
        self.set_LICA_Button.setText(_translate("MainWindow", "LICA"))
        self.set_LVA_Button.setText(_translate("MainWindow", "LVA"))
        self.set_RECA_Button.setText(_translate("MainWindow", "RECA"))
        self.set_RICA_Button.setText(_translate("MainWindow", "RICA"))
        self.set_RVA_Button.setText(_translate("MainWindow", "RVA"))
        self.set_LCCA_Button.setText(_translate("MainWindow", "LCCA"))
        self.set_RCCA_Button.setText(_translate("MainWindow", "RCCA"))
        self.set_CCAp_Button.setText(_translate("MainWindow", "LAT_CCAp"))
        self.set_CCAd_Button.setText(_translate("MainWindow", "LAT_CCAd"))
        self.set_LSUBA_Button.setText(_translate("MainWindow", "LSUBA"))
        self.set_RSUBA_Button.setText(_translate("MainWindow", "RSUBA"))
        self.set_ARCH_Button.setText(_translate("MainWindow", "ARCH"))
        self.set_LAT_ECA_Button.setText(_translate("MainWindow", "LAT_ECA"))
        self.set_LAT_ICA_Button.setText(_translate("MainWindow", "LAT_ICA"))
        self.set_LAT_VA_Button.setText(_translate("MainWindow", "LAT_VA"))
        self.lastImg_Button.setText(_translate("MainWindow", "Last Image"))
        self.load_Button.setText(_translate("MainWindow", "load json"))
        self.dump_json_Button.setText(_translate("MainWindow", "Save Json"))
        self.accept_Button.setText(_translate("MainWindow", "Accept"))
        self.remove_Button.setText(_translate("MainWindow", "Remove"))
        self.set_UnknownAP_Button.setText(_translate("MainWindow", "Unknown AP"))
        self.set_UnknownLAT_Button.setText(_translate("MainWindow", "Unknown LAT"))
        self.PrimaryAngel_label.setText(_translate("MainWindow", "TextLabel"))

